const { chromium } = require('@playwright/test');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('http://localhost:3001', {waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Industries',exact:true}).click();
 await page.locator('.mobility-explorer').waitFor();
 await page.locator('.mobility-parent').filter({hasText:'Railways'}).click();
 await page.locator('.mobility-results h3').filter({hasText:'Coach'}).waitFor();
 if(await page.locator('.mobility-results a').count()!==6) throw Error('Missing solutions');
 await page.screenshot({path:'mobility-redesign-desktop.png'});
 await page.locator('.mobility-parent').filter({hasText:'Automobiles'}).click();
 await page.getByRole('button',{name:'Commercial Vehicle',exact:true}).click();
 await page.locator('.mobility-results h3').filter({hasText:'Commercial Vehicle'}).waitFor();
 await page.locator('.mobility-results a').first().click();
 await page.waitForURL('**/products/panel-filter');
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://localhost:3001',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Open menu'}).click();
 await page.getByRole('button',{name:'Industries',exact:true}).click();
 await page.locator('.mobility-parent').filter({hasText:'Railways'}).click();
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Mobile overflow');
 const panel = await page.locator('.mobility-results').boundingBox();
 if(!panel || panel.x<0 || panel.x+panel.width>390) throw Error('Results outside viewport');
 await page.locator('.mobility-results').scrollIntoViewIfNeeded();
 await page.screenshot({path:'mobility-redesign-mobile.png'});
 if(errors.length)throw Error(errors.join('; '));
 console.log('PASS: desktop and mobile, vehicle selection, six product links, navigation, no overflow or browser errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
