import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight, Check, ArrowRight } from 'lucide-react';
import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import StructuredData from '../../../components/StructuredData';
import {buyerResources} from '../../../lib/buyer-resources';
import {products} from '../../../lib/products';
import {pageMetadata,breadcrumb,webPageSchema} from '../../../lib/seo';
export function generateStaticParams(){return buyerResources.map(r=>({slug:r.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const resource=buyerResources.find(r=>r.slug===slug);return resource?pageMetadata(resource.title+' | PARK',resource.description,'/resources/'+slug):{title:'Guide not found',robots:{index:false}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const resource=buyerResources.find(r=>r.slug===slug);if(!resource)notFound();
 const related=products.filter(p=>resource.products.includes(p.slug));
 return <><Header/><main id="main-content" className="section resource-detail"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/resources">Resources</Link><span>/</span><span>Buying guide</span></nav><div className="resource-article-header"><div className="eyebrow">{resource.kicker} / {resource.readTime}</div><h1>{resource.title}</h1><p className="lead">{resource.intro}</p></div><div className="resource-article-layout"><article><div className="resource-takeaways"><span className="eyebrow">WHAT TO KEEP IN MIND</span>{resource.takeaways.map(text=><p key={text}><Check size={17}/>{text}</p>)}</div>{resource.sections.map((section,index)=><section className="resource-article-section" id={'step-'+(index+1)} key={section.title}><span className="resource-section-index">0{index+1}</span><h2>{section.title}</h2>{section.paragraphs.map(text=><p key={text}>{text}</p>)}{section.checks&&<ul className="resource-checklist">{section.checks.map(check=><li key={check}><Check size={16}/>{check}</li>)}</ul>}</section>)}<section className="resource-question"><h2>A question buyers ask</h2><details open><summary>{resource.question}</summary><p>{resource.answer}</p></details></section><div className="resource-source-note">Guidance based on the PARK product catalogue. Confirm selected media, fit, grade and operating conditions with the team before ordering.</div></article><aside className="resource-sidebar"><span className="eyebrow">IN THIS GUIDE</span><nav aria-label="Guide contents">{resource.sections.map((section,index)=><a key={section.title} href={'#step-'+(index+1)}><span>0{index+1}</span>{section.title}</a>)}</nav><div className="resource-sidebar-enquiry"><h3>Move from a question<br/>to a specification.</h3><p>Share your system details and discuss the available product options.</p><Link href="/#contact">Discuss your application <ArrowUpRight size={16}/></Link></div></aside></div><section className="resource-related"><div className="section-heading"><h2>Explore the relevant products</h2><Link href="/products" className="underlined-link">Compare the range <ArrowRight size={16}/></Link></div><div className="product-grid">{related.map(p=><Link key={p.slug} href={'/products/'+p.slug} className="product-card"><div className="product-image"><img src={'/images/'+p.image+'.webp'} alt={p.name} width={480} height={360} loading="lazy"/></div><div className="product-info"><h3>{p.name}</h3><p>{p.description}</p></div></Link>)}</div></section><Link className="underlined-link" href="/resources">Explore more buying guides <ArrowRight size={17}/></Link></main><StructuredData data={breadcrumb([{name:'Home',path:'/'},{name:'Resources',path:'/resources'},{name:resource.title,path:'/resources/'+slug}])}/><StructuredData data={webPageSchema(resource.title,resource.description,'/resources/'+slug)}/><Footer/></>
}
