'use client';
import NextImage from 'next/image';
import {useState} from 'react';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Wind, Factory, CarFront, Droplets, Check, MousePointer2 } from 'lucide-react';
import {products} from '../lib/products';
const paths=[
 {name:'HVAC & controlled air',icon:Wind,tone:'teal',label:'BUILD A CLEARER AIR PATH',title:'Protect the air.<br/>Support the process.',text:'From incoming air to a controlled environment, every filtration stage has a job. Explore the panel, pocket and fine-filtration formats available for your air-handling system.',slugs:['panel-filter','pocket-filter','hepa-filter'],roles:['Panel format','Extended-surface format','Fine-filtration options'],caption:'Illustrative product roles. Confirm the stage arrangement and selected grades for your system.',need:'Airflow, grade, frame dimensions, pressure-drop limit and sealing arrangement.',guide:'panel-pocket-hepa-air-filters'},
 {name:'Industrial dust',icon:Factory,tone:'amber',label:'KEEP YOUR PROCESS IN FOCUS',title:'Demanding dust.<br/>A considered filter choice.',text:'Cement, power, chemicals and production processes can place very different demands on a dust collector. Compare bag and cartridge assemblies, then match the media to the process and collector.',slugs:['bag-filter','cartridge-filter'],roles:['Bag collector format','Pleated cartridge format'],caption:'Alternative collector formats. These are not automatically interchangeable.',need:'Collector model, dust characteristics, temperature, cleaning arrangement and mounting details.',guide:'bag-vs-cartridge-dust-collection'},
 {name:'Vehicle cabins',icon:CarFront,tone:'blue',label:'MAKE EVERY JOURNEY A CLEARER ONE',title:'Passenger comfort.<br/>Filtration with a purpose.',text:'Cabin ventilation and an in-car purifier are different systems. Explore particle, activated-carbon and fine-filtration options, and specify the contaminant you want to address.',slugs:['cabin-air-filter','car-purifier-filter'],roles:['Cabin ventilation','In-car purifier'],caption:'Two different vehicle air systems. Confirm vehicle fit and variant-specific performance.',need:'Vehicle or purifier model, existing part reference, dimensions and particle or odour requirement.',guide:null},
 {name:'Process liquids',icon:Droplets,tone:'lime',label:'PARTICLE CONTROL FOR YOUR LIQUID PATH',title:'Cleaner liquids.<br/>A better-defined specification.',text:'Retain suspended particles in process water, coolants and other liquid applications. Start with the fluid conditions, required particle rating and housing fit to discuss a suitable liquid bag assembly.',slugs:['liquid-filter'],roles:['Suspended-particle removal'],caption:'Confirm fluid compatibility, flow, selected micron rating and housing seal.',need:'Liquid identity, temperature, flow, particle rating, bag dimensions and sealing-ring details.',guide:'liquid-bag-filter-selection'},
];
export default function ApplicationStudio(){
 const [selected,setSelected]=useState(0);const path=paths[selected];
 return <section className="section application-studio" id="application-studio"><div className="section-heading"><div><div className="eyebrow"><MousePointer2 size={15}/> EXPLORE THE APPLICATION</div><h2>What are you<br/><span>protecting?</span></h2></div><p>A process. A passenger. A production environment.<br/>See how the filter choice changes with the job.</p></div><div className="studio-controls" role="group" aria-label="Explore filtration applications">{paths.map((entry,index)=>{const Icon=entry.icon;return <button key={entry.name} aria-pressed={selected===index} onClick={()=>setSelected(index)}><Icon size={18}/>{entry.name}<ArrowUpRight size={15}/></button>})}</div><div className={'studio-panel studio-'+path.tone} aria-live="polite" aria-atomic="true"><div className="studio-story" key={path.name}><span className="studio-kicker">{path.label}</span><h3>{path.title.split('<br/>').map((line,index)=><span key={line}>{index>0&&<br/>}{line}</span>)}</h3><p>{path.text}</p><div className="studio-spec"><Check size={17}/><div><strong>What helps us specify it</strong><p>{path.need}</p></div></div><Link href={path.guide?'/resources/'+path.guide:'/products/cabin-air-filter'} className="studio-guide">{path.guide?'Understand the selection':'Explore cabin filter variants'} <ArrowRight size={16}/></Link></div><div className="studio-product-path"><div className={'studio-product-cards studio-count-'+path.slugs.length}>{path.slugs.map((slug,index)=>{const p=products.find(product=>product.slug===slug)!;return <Link className="studio-product" href={'/products/'+slug} key={slug}><span className="studio-product-step">0{index+1} / {path.roles[index]}</span><NextImage sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 640px" src={'/images/'+p.image+'.webp'} alt={p.name} width={480} height={360} loading="lazy"/><div><h4>{p.name}</h4><ArrowUpRight size={18}/></div><span className="studio-product-action">Explore product &amp; 3D view</span></Link>})}</div><p className="studio-caption">{path.caption}</p><Link href="/#contact" className="button studio-enquiry">Discuss this application <ArrowUpRight size={18}/></Link></div></div></section>
}
