import Link from 'next/link';
import {ArrowUpRight, Layers, ScanLine, FileCheck2} from 'lucide-react';
const questions=[
 ['Which filter is right for my application?','Start with what you need to remove and where the filter will be installed. Explore our product catalogue, then share your system details with PARK to discuss media, grade and fit.'],
 ['Can PARK help with a replacement or custom filter size?','Yes. Send the existing filter dimensions, housing details or a drawing, along with the quantity. Our range includes standard and customer-specific formats; our team can discuss available options for your selected product.'],
 ['What should I check before placing an order?','Confirm dimensions, media, grade, sealing or mounting, and suitability for the operating conditions. For air, include airflow and pressure-drop requirements. For liquids, include the fluid identity, flow, temperature and particle rating.'],
 ['Can I compare products before making an enquiry?','Yes. The product catalogue lets you shortlist and compare up to three product families. Use the comparison to understand the differences, then send your system requirements to discuss the selected assembly.'],
];
export default function BuyerConfidence(){return <><section className="section buyer-confidence"><div className="section-heading"><div><div className="eyebrow">FROM EXPLORATION TO ENQUIRY</div><h2>Why choose PARK?<br/><span>Clear options. Useful guidance.</span></h2></div><Link href="/products" className="button">Explore &amp; compare products <ArrowUpRight size={17}/></Link></div><div className="confidence-grid">{[{icon:Layers,title:'Understand your options',text:'See product photos, materials and construction details so you can compare filters for the job you need them to do.',label:'Explore product families',href:'/products'},{icon:ScanLine,title:'Choose around your system',text:'Compare media, grades and formats against your airflow, dust load or liquid conditions. Start with what your equipment needs.',label:'Read the selection guide',href:'/resources/filter-selection'},{icon:FileCheck2,title:'Speak directly with our team',text:'Send your dimensions, operating conditions and quantity to PARK. Discuss product fit and the information you need before ordering.',label:'Discuss your requirement',href:'/#contact'}].map((entry,index)=><article key={entry.title}><span className="confidence-step">0{index+1}</span><entry.icon size={27} strokeWidth={1.4}/><h3>{entry.title}</h3><p>{entry.text}</p><Link href={entry.href}>{entry.label}<ArrowUpRight size={16}/></Link></article>)}</div></section><section className="section home-buyer-faq"><div><div className="eyebrow">BEFORE WE GET STARTED</div><h2>Questions about filters?<br/><span>Start here.</span></h2><p>Not sure which filter you need? These answers help you take the next step.</p><Link href="/#contact" className="underlined-link">Talk about your filtration needs <ArrowUpRight size={16}/></Link></div><div>{questions.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section></>}
