'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, ArrowDown, Wind, Layers3, Leaf, MoveUpRight, Check, Plus } from 'lucide-react';
import HeroFilm from './HeroFilm';
import IndustryFilm from './IndustryFilm';
import ApplicationStudio from './ApplicationStudio';
import BuyerResources from './BuyerResources';
import BuyerConfidence from './BuyerConfidence';
import {mediaLayers} from '../lib/media-architecture';
import MediaArchitecture from './MediaArchitecture';
import MediaExplorer from './MediaExplorer';import Header from './Header';import Footer from './Footer';import Catalogue from './Catalogue';import Contact from './Contact';import { industries, products } from '../lib/products';
export default function Home(){const [selected,setSelected]=useState(0);const industry=industries[selected];return <><Header/><main id="main-content"><section className="hero"><HeroFilm/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><span className="green-dot"/>PARK NONWOVEN / AIR &amp; LIQUID FILTRATION</div><h1>One stop solution<br/><span>for filtration</span></h1><p className="hero-value">Dust in your air system? Particles in your process liquid? PARK Nonwoven helps you find filters and media that fit your equipment, your working conditions and the job you need them to do.</p><div className="hero-actions"><Link href="/products" className="button white">Explore filtration products <ArrowUpRight size={19}/></Link><a href="#contact" className="text-link">Discuss your requirement <ArrowRight size={17}/></a></div></div><div className="hero-bottom"><span>YOUR AIR. YOUR EQUIPMENT. YOUR PROCESS. FIND THE RIGHT FILTER.</span><a href="#about" aria-label="Scroll to discover"><ArrowDown size={18}/><span>Scroll to discover</span></a></div><div className="hero-side">AIR FILTERS / LIQUID FILTERS / NONWOVEN MEDIA</div></section><div className="benefits"><div><Wind/><span>Air filtration.<b>Manage dust and particles.</b></span></div><div><Layers3/><span>Liquid filtration.<b>Remove suspended solids.</b></span></div><div><Leaf/><span>Nonwoven media.<b>Match your application.</b></span></div></div>
<section id="about" className="section intro"><div><div className="eyebrow">YOUR FILTRATION PARTNER</div><h2>Your filtration problem.<br/><span>Our starting point.</span></h2></div><div><p>Choosing a filter should start with what is going wrong: dust reaching equipment, particles affecting a process, or a replacement that does not fit. At PARK Nonwoven, we help you work through the application and compare suitable air filters, liquid bag filters and nonwoven media.</p><p>Our range covers vehicle filtration, HVAC systems, industrial dust collection and process liquids. Share your current filter, dimensions and operating conditions so we can discuss the material, grade and format your system needs.</p><a className="underlined-link" href="#technology">Discover our approach <ArrowUpRight size={18}/></a><div className="range-proof" aria-label="Explore the PARK catalogue range"><div><strong>{products.length}</strong><span>Product families</span></div><div><strong>{industries.length}</strong><span>Industry groups</span></div><div><strong>{mediaLayers.reduce((count,group)=>count+group.items.length,0)}</strong><span>Media design options</span></div></div></div></section>
<section id="industries" className="section industry-section"><div className="section-heading"><div><div className="eyebrow">SOLUTIONS FOR YOUR WORKING ENVIRONMENT</div><h2>Filtration for the way<br/>your industry works.</h2></div><p>Start with the problem in your system.<br/>Explore filters for your application.</p></div><div className="industry-layout"><div className="industry-list">{industries.map((item,i)=><button key={item.name} aria-pressed={i===selected} className={i===selected?'selected':''} onMouseEnter={()=>{if(window.matchMedia('(hover:hover) and (pointer:fine)').matches)setSelected(i);}} onFocus={()=>setSelected(i)} onClick={()=>setSelected(i)}><span className="number">0{i+1}</span><span>{item.name}</span><ArrowUpRight size={22}/></button>)}</div><div className={`industry-visual industry-${selected}`}><IndustryFilm key={industry.name} industry={industry.name}/><div key={'overlay-'+industry.name} className="industry-overlay"><span>0{selected+1} / 05</span><h3>{industry.label}</h3><p>{industry.description}</p><Link href={`/industries/${industry.name.toLowerCase().replaceAll(' ','-')}`} className="text-link">Explore {industry.name.toLowerCase()} <ArrowUpRight size={18}/></Link></div></div></div></section>
<section className="section products-section"><div className="section-heading"><div><div className="eyebrow">AIR FILTERS, LIQUID FILTERS &amp; MEDIA</div><h2>Find your filtration solution.</h2></div><Link href="/products" className="underlined-link">View all products <ArrowUpRight size={18}/></Link></div><Catalogue compact/></section>
<ApplicationStudio/><section id="technology" className="technology"><div className="tech-visual"><div className="fiber-lines"/><span className="tech-caption">THE BUILDING BLOCKS OF BETTER FILTRATION</span><div className="tech-title">Engineered<br/>from the<br/><em>fiber up.</em></div><div className="tech-bottom"><span>FIBER → MEDIA → FILTER</span><Plus size={32}/></div></div><div className="tech-copy"><div className="eyebrow">WHAT TO LOOK FOR IN FILTER MEDIA</div><h2>Particle capture.<br/>Flow. Service life.</h2><p>The right filter needs to capture unwanted particles while allowing your system to work. We help you compare three important factors when selecting nonwoven filtration media.</p>{[{n:'01',title:'Filtration efficiency',text:'Which particles need to be removed? Match the filtration grade to the air-quality or process requirement.'},{n:'02',title:'Pressure drop',text:'How much resistance can your system handle? Consider airflow and pressure drop together when choosing a filter.'},{n:'03',title:'Dust-holding capacity',text:'How much dust reaches the filter? Consider the dust load and replacement interval alongside the required efficiency.'}].map(x=><div className="tech-point" key={x.n}><span>{x.n}</span><div><h3>{x.title}</h3><p>{x.text}</p></div><Check size={18}/></div>)}<div className="material-tags"><span>Meltblown</span><span>Needle punch</span><span>Thermo bonding</span><span>Spunlaid</span></div></div></section>
<MediaArchitecture/><MediaExplorer/><section className="section process"><div className="section-heading"><div><div className="eyebrow">HOW WE HELP YOU CHOOSE</div><h2>From your problem to a filter shortlist.</h2></div><p>A practical conversation about your needs.<br/>A clearer specification for your order.</p></div><div className="process-grid">{[{t:'Tell us what is happening',s:'01 / YOUR CHALLENGE',d:'Describe the particles, application and problem you want to solve.'},{t:'Share your system details',s:'02 / YOUR EQUIPMENT',d:'Include filter dimensions, flow, temperature and your current specification.'},{t:'Compare suitable options',s:'03 / YOUR FILTER OPTIONS',d:'Review media, grade, construction and fit for your operating conditions.'},{t:'Discuss your requirement',s:'04 / YOUR NEXT STEP',d:'Send your shortlist and quantity to our team for a product enquiry.'}].map(x=><div key={x.s}><span>{x.s}</span><MoveUpRight/><h3>{x.t}</h3><p>{x.d}</p></div>)}</div></section>
<section className="section media-capabilities"><div><div className="eyebrow">NONWOVEN FILTRATION MEDIA</div><h2>From material to finished filter.</h2><p>Need filter media rather than a finished filter? Explore material, construction and treatment options for your application, from pre-filtration to fine particle capture.</p><div className="capability-columns"><div><h3>Materials</h3><p>Polyester (PET), polypropylene (PP), glass fiber and activated carbon.</p></div><div><h3>Technologies</h3><p>Spunlaid, meltblown, needle punch and thermo bonding.</p></div><div><h3>Enhancements</h3><p>Antimicrobial, electret and bio-functional options; coloring, impregnation and lamination.</p></div></div><Link className="underlined-link" href="/filtration-media">Explore materials and technologies <ArrowUpRight size={18}/></Link></div><div className="media-product-visual"><img src="/images/image24.webp" alt="PARK pleated panel air filter" width={640} height={480} loading="lazy"/><span>Fiber / Nonwoven process / Media / Filter</span></div></section>{process.env.NEXT_PUBLIC_FILTRATION_VIDEO && <section className="section filtration-film"><div className="eyebrow">SEE FILTRATION IN ACTION</div><h2>Explore PARK filtration</h2><video controls playsInline preload="none" poster="/images/image24.webp" aria-label="PARK filtration overview"><source src={process.env.NEXT_PUBLIC_FILTRATION_VIDEO} type="video/mp4"/>{process.env.NEXT_PUBLIC_FILTRATION_CAPTIONS && <track kind="captions" src={process.env.NEXT_PUBLIC_FILTRATION_CAPTIONS} srcLang="en" label="English" default/>}Your browser does not support video.</video></section>}<section className="section catalogue-invitation"><div><div className="eyebrow">CHOOSE WITH CLEAR PRODUCT INFORMATION</div><h2>Know what you are choosing.<br/>Know what to ask.</h2><p>See how each filter works, where it is used and which technical options are available. Compare your shortlist, then discuss dimensions, media and operating requirements with PARK.</p></div><div><Link href="/products" className="button">Explore and compare products <ArrowUpRight size={18}/></Link><Link href="/resources/filter-selection" className="underlined-link">Understand how to choose a filter <ArrowUpRight size={16}/></Link></div></section><BuyerResources/><BuyerConfidence/><Contact/></main><Footer/></>}
