export type BuyerResource = {
 slug:string; title:string; description:string; kicker:string; readTime:string;
 intro:string; takeaways:string[];
 sections:{title:string;paragraphs:string[];checks?:string[]}[];
 products:string[]; question:string; answer:string;
};
// Buyer guidance developed from PARK's supplied catalogue and product explanations.
// No prices, measured performance, certifications or service-life claims are inferred.
export const buyerResources:BuyerResource[]=[
 {
  slug:'panel-pocket-hepa-air-filters',title:'Panel, Pocket or HEPA? Choose the Right Air Filtration Stage',
  description:'Compare panel, pocket and fine-filtration formats for HVAC and controlled-air systems. Understand media grade, airflow, sealing and what to send for a quote.',
  kicker:'HVAC & CONTROLLED AIR',readTime:'5 min read',
  intro:'A building or production air system needs more than a filter that fits the opening. The filter format, particle requirement, available airflow and installation seal need to work together. PARK offers panel, pocket and fine-filtration options; start by identifying the job of the stage you are specifying.',
  takeaways:['Format describes construction; grade describes a filtration requirement.','Airflow and pressure drop belong in the same specification.','A staged arrangement must match the actual air-handling system.'],
  sections:[
   {title:'Start with the air system, not the highest grade',paragraphs:['Identify whether the filter is for outdoor-air intake, railway ventilation, a commercial air-handling unit, paint-booth ventilation or a controlled production environment. These applications have different filter housings and particle-control needs.','Record the existing filter reference, the stage being replaced and the performance requested by the system designer. A catalogue range is a list of available options, not proof that every option is appropriate for your equipment.']},
   {title:'Panel filters: a compact pleated format',paragraphs:['Panel filters use pleated media within a supporting frame. PARK lists synthetic nonwoven media, metal or plastic frames and standard or special-size options. Catalogue applications include HVAC, railway ventilation, commercial buildings and cleanroom ventilation.','Confirm the overall width, height and depth, frame construction, seal and airflow. A panel describes the physical assembly; it does not identify one universal particle-efficiency class.']},
   {title:'Pocket filters: extended surface for air handling',paragraphs:['Pocket filters provide an extended-surface arrangement in an air-handling unit. The pocket media retain dust and airborne particles as air passes through them. Media selection and system airflow determine the resistance of the selected assembly.','Check the pocket depth and arrangement as well as the frame size. PARK lists hospitals, laboratories, paint booths and industrial ventilation among the applications. An HVAC pocket filter is different from an industrial dust-collection bag filter.']},
   {title:'Fine filtration: specify the exact grade and seal',paragraphs:['The PARK fine-filtration range lists E10, E11, E12, H13, H14 and U15 options with EN 1822 and ISO 29463 catalogue references. These are different classifications. Ask for the selected filter grade and its supporting report rather than applying one efficiency number to the whole range.','Media performance is only part of the assembly. Confirm the housing, seal, dimensions and operating airflow to address bypass around the filter. Particle filtration should not be treated as gas adsorption or a guarantee of infection prevention.']},
   {title:'Compare the whole filtration stage',paragraphs:['A staged system may use an upstream filter to retain larger contamination before a fine-filtration stage. The arrangement depends on the equipment design; adding stages or changing a grade can change the system resistance.','Share the current arrangement with the team. Discuss performance at the required airflow, the available pressure-drop limit and the planned maintenance approach. Do not choose a replacement by image or nominal dimensions alone.'],checks:['Overall frame size, depth and sealing arrangement','Required airflow and acceptable pressure drop','Selected grade and filter-specific technical evidence','System drawing or existing part reference','Quantity and standard or custom format']},
  ],products:['panel-filter','pocket-filter','hepa-filter','filter-mats'],question:'Can I upgrade to a finer filter without changing anything else?',answer:'Suitability depends on the housing, airflow, fan capability, pressure-drop allowance and required grade. Share the current filter and system details so these can be checked before selecting a replacement.'
 },
 {
  slug:'bag-vs-cartridge-dust-collection',title:'Bag vs Cartridge Filters for Industrial Dust Collection',
  description:'Compare industrial bag and cartridge filter formats. Learn which dust, temperature, media and collector details to confirm before requesting a quotation.',
  kicker:'INDUSTRIAL DUST COLLECTION',readTime:'5 min read',
  intro:'Dust collection is a process-equipment decision. A bag and a cartridge both retain particles, but their construction and mounting need to match the collector and the process. Start with the dust characteristics and equipment details, then confirm the media and assembly.',
  takeaways:['Choose for the collector, not the product name alone.','Dust properties and operating conditions guide media selection.','Neither format is a universal replacement for the other.'],
  sections:[
   {title:'Understand the dust and the collection point',paragraphs:['Describe where the dust is generated: cement handling, power generation, chemical processing, metalworking, powder handling or another production process. Include whether conditions vary during start-up, normal operation or cleaning.','Record the dust characteristics and the operating information you have. If the process has a documented fire, combustible-dust or other safety requirement, include that specification in the enquiry so equipment and media suitability can be assessed by the responsible system specialist.']},
   {title:'Industrial bag filters: media shaped for the collector',paragraphs:['PARK lists industrial bag filters for continuous industrial dust collection. The catalogue includes PET, PPS, PTFE, glass fibre, aramid, polypropylene, homopolymer acrylic and P84 media options. Availability of a material does not confirm its suitability for a particular process.','A bag assembly needs the correct dimensions, mounting, ring and supporting arrangement. Share a drawing or existing part details. Confirm the selected medium against the actual process conditions rather than assuming all listed media have the same operating limits.']},
   {title:'Cartridge filters: match the collector',paragraphs:['PARK lists cartridge filters for industrial dust collection and high-dust-load applications, including cement, steel and metals, power plants, chemical processing and general manufacturing.','Confirm the selected cartridge construction with our team. The fit and performance depend on the collector design, dust load, cleaning method and chosen media. Confirm the mounting and seal as well as the overall diameter and length.']},
   {title:'Compare what the collector can actually accept',paragraphs:['A bag collector and a cartridge collector can have different mounting and cleaning arrangements. A filter that appears similar may still be incompatible with the support, end cap, seal or available installation clearance.','Provide the collector manufacturer or model where known, the existing filter reference and the cleaning arrangement. Ask for a confirmed assembly rather than treating the two formats as interchangeable. An HVAC pocket filter is also a separate product family, despite the similar bag-shaped appearance.']},
   {title:'Build a complete enquiry',paragraphs:['The quotation should identify both the assembly and the process conditions. This gives the team a useful basis for selecting an available medium and confirming the construction.','Plan inspection and replacement around the equipment guidance and operating evidence. Dust loads and conditions vary; a catalogue description cannot establish a fixed service interval for every site.'],checks:['Dust or process description and collector model','Existing filter dimensions, mounting and seal details','Temperature and relevant chemical exposure','Flow requirement and pressure conditions, if available','Cleaning method, quantity and an existing drawing']},
  ],products:['bag-filter','cartridge-filter'],question:'Which format lasts longer?',answer:'Service life depends on the selected media, dust load, operating conditions, cleaning arrangement and maintenance. A universal bag-versus-cartridge life comparison would be misleading. Compare the assemblies under the conditions of your collector.'
 },
 {
  slug:'liquid-bag-filter-selection',title:'How to Specify a Liquid Bag Filter for Your Process',
  description:'Choose a liquid bag filter by fluid, micron rating, flow, housing dimensions and sealing ring. Prepare an enquiry for process water, coolant or particle removal.',
  kicker:'LIQUID & PROCESS FILTRATION',readTime:'4 min read',
  intro:'A micron value is only one part of a liquid-filter specification. The fluid, operating temperature, flow, housing and sealing arrangement also matter. PARK offers polypropylene liquid bag filters with customer-specific formats and sealing-ring options for particle-removal applications.',
  takeaways:['Identify the liquid and particles before choosing a rating.','Confirm the complete bag and ring fit in the housing.','Particle removal is different from dissolved-contaminant treatment.'],
  sections:[
   {title:'Define what needs to be removed',paragraphs:['Describe the suspended particles or contamination in the liquid and the downstream equipment you want to protect. Catalogue applications include process water, machine coolants, wastewater, and food or pharmaceutical processes.','A bag filter retains particles as the liquid passes through the media. It should not be described as removing every dissolved substance or replacing all other water-treatment stages. Share any specific quality requirement so the filtration role can be confirmed.']},
   {title:'Treat micron ratings as a specification to verify',paragraphs:['The supplied PARK liquid-filter entry lists 1.5, 2.5, 7.5, 10 and 34 micrometre options. Confirm the available selected rating, the test basis and the retention required by your process. These values describe catalogue options, not one fixed performance level.','A smaller listed number alone does not confirm the best filter. Discuss the contaminant load, required flow and pressure conditions, as well as the performance evidence for the selected medium.']},
   {title:'Match media to the actual fluid conditions',paragraphs:['PARK lists polypropylene media for liquid bag filters. Confirm compatibility with the liquid identity, concentration where relevant, temperature and any chemical exposure. Do not infer compatibility from a broad industry category.','For food, pharmaceutical or another controlled process, include the application-specific documentation requirements in the enquiry. A listed application is not a substitute for confirming the selected product and the evidence your process requires.']},
   {title:'Check the bag, ring and housing together',paragraphs:['The catalogue includes polypropylene or stainless-steel sealing-ring options and customer-specific bag sizes. Record the housing make or model, bag diameter and length, ring dimensions and the installation arrangement.','Include an existing drawing or part reference if you have one. The seal needs to suit the housing; bypass around an incorrectly fitted bag can undermine the intended particle-removal function.']},
   {title:'Send the details that move a quotation forward',paragraphs:['A useful enquiry combines fluid conditions with the exact assembly. If some information is not known, say which details are available and which need confirmation.','Replacement planning depends on the process and operating evidence. Ask for the selected product information and follow the equipment guidance rather than assuming a fixed replacement interval.'],checks:['Liquid identity, temperature and relevant concentration','Contaminant description and required particle rating','Flow and pressure information','Housing reference, bag dimensions and ring arrangement','Quantity and process documentation requirements']},
  ],products:['liquid-filter'],question:'Does a liquid bag filter remove dissolved chemicals?',answer:'The catalogue liquid bags are described for suspended-particle removal. Do not assume removal of dissolved chemicals or all microbial contaminants. Specify the contaminant and required treatment result so the filtration role can be confirmed.'
 },
];
export const resourceForProduct=(slug:string)=>buyerResources.find(resource=>resource.products.includes(slug));
