export const applicationDescriptions: Record<string,string> = {
  "Automobiles": "Dust, pollen and road debris affect different parts of a vehicle. PARK offers cabin, engine intake, battery cooling and car purifier filters. Tell us which system you are working on to discuss the correct format and media.",
  "Railways": "Coach ventilation needs filters that fit the air-handling system and its maintenance requirements. Explore PARK panel filters and nonwoven filter mats, then share your dimensions, airflow and required grade.",
  "Pharmaceutical": "Airborne particles and process-liquid contaminants call for different filtration stages. Explore pre-filters, fine air filters and liquid bag filters with PARK, and discuss the grade and documentation your process requires.",
  "Paint Booth": "Dust in the air supply can affect a paint finish. Explore filter mats, pocket filters and ceiling filters for your booth. Share the filtration stage, booth dimensions and airflow to discuss a suitable option.",
  "Food Industry": "Your air-handling and liquid processes have different filtration needs. PARK offers air filters and liquid bag filters to help manage particles. Share the process conditions and any food-contact requirements with our team.",
  "Electronics & Optics": "Particle control matters when working with sensitive components and optical surfaces. Explore air-handling and fine-filtration options, then discuss your required cleanliness level, airflow and filter housing.",
  "Power Plant": "Managing process dust and protecting ventilation equipment need different filter designs. Explore industrial bags, cartridges, panel filters and pocket filters. Tell us about the dust, temperature and system you need to filter.",
  "Cement Plant": "High dust loads make filter material and collector fit important. PARK offers industrial bag and cartridge options. Share the dust characteristics, process temperature and attachment dimensions to discuss your installation.",
  "Chemical Industry": "Chemical exposure, dust and operating temperature influence filter selection. Explore air-handling and industrial dust-collection options with PARK, and discuss material compatibility for your process.",
  "House": "Looking for a replacement ventilation filter? Start with your existing filter dimensions and system requirements. PARK offers indoor air-filtration options, with swimming pool filters also included in the living range.",
  "Hotel": "Guest rooms, shared spaces and service areas depend on well-maintained ventilation. Explore panel, pocket and fine air filters for your HVAC system. For pool circulation, discuss a separate pool-filter specification.",
  "Retail and Commercial Building": "Keep dust and airborne particles in view when choosing filters for offices, shops and commercial spaces. Compare PARK panel and pocket filters against your air-handling unit, airflow and replacement requirements.",
  "Hospital": "Different hospital areas have different air-filtration requirements. PARK offers panel, pocket and fine-filtration options. Discuss the filtration stage, required grade, installation seal and supporting documentation for your system.",
  "Pharma": "Need to remove suspended particles from a process liquid? Explore PARK polypropylene liquid bag filters and sealing-ring options. Share the fluid, particle rating, flow, temperature and housing details to discuss suitability."
};
