import MediaProcessFilm from '../../components/MediaProcessFilm';
import Link from 'next/link';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import MediaExplorer from '../../components/MediaExplorer';
import MediaArchitecture from '../../components/MediaArchitecture';
import { pageMetadata } from '../../lib/seo';
export const metadata=pageMetadata('Nonwoven Filter Media & Filtration Materials | PARK', 'Explore nonwoven filter media, polyester, polypropylene and activated carbon options. Discuss material, construction and filtration needs with PARK Nonwoven.', '/filtration-media');
const groups=[
 {name:'Materials',items:[["PET / polyester","Explore polyester nonwoven media for air pre-filtration and industrial filter applications. Discuss the thickness, construction and operating temperature your system needs."],["PP / polypropylene","Polypropylene is available in our media range and liquid bag filters. Share your fluid and operating conditions to discuss compatibility, particle rating and format."],["Glass fibre","Our fine air-filtration range includes borosilicate micro glass fibre with synthetic components. Discuss the particle grade, airflow and finished filter construction."],["Activated carbon","Need to address odours or certain gases as well as particles? Explore activated carbon options in our vehicle filtration range. The target contaminant guides the choice."]]},
 {name:'Technologies',items:[["Spunlaid","Explore spunlaid construction as part of the PARK nonwoven media range. Discuss the structure and finished format needed for your filter design."],["Meltblown","Meltblown is one of our nonwoven filtration technology options. Tell us about the particle-capture and flow requirements to discuss a suitable media grade."],["Needle punch","Explore needle-punched nonwoven options for your filtration task. Discuss the material, construction and operating conditions with our team."],["Thermo bonding","Thermo-bonded media is part of our nonwoven technology range. Share the media structure and finished filter requirements you are working towards."]]},
 {name:'Enhancements',items:[["Antimicrobial","Discuss antimicrobial treatment options for the selected medium, including intended use and product-specific performance information."],["Electret","Explore electret media options where particle capture is part of your requirement. Ask our team about the chosen grade and its performance data."],["Bio-functional","Our cabin-filter range includes bio-functional media options for allergen-related filtration needs. Discuss the selected variant and its supporting product information."],["Colouring","Need a particular media colour? Discuss available finishes for your selected material and format."],["Impregnation","Explore impregnation options for the function your filter media needs to provide. Share the application and treatment requirements."],["Lamination","Need several media layers in one assembly? Discuss layer combinations and lamination options for your filter construction."]]}
];
export default function MediaPage(){return <><Header/><main id="main-content"><section className="section media-page-intro"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Filtration media</span></nav><div className="eyebrow">FILTER MEDIA FOR YOUR APPLICATION</div><h1>Nonwoven filter media.<br/>Start with your application.</h1><p className="lead">The material inside a filter affects what it captures and how air or liquid moves through it. PARK helps you explore nonwoven filtration media by material, construction and treatment, so you can discuss a combination that suits your system.</p><div className="media-path"><span>Fibre / pulp / glass fibre</span><b>→</b><span>Nonwoven process</span><b>→</b><span>Filter media</span><b>→</b><span>Finished filter</span></div></section><MediaProcessFilm/><MediaArchitecture/><MediaExplorer/><section className="section media-library"><h2>Choose the material behind your filter</h2><p>Need a media roll, a custom cut or a finished filter? Explore the options below, then tell us what you need to remove, the required flow and the conditions the media will face.</p>{groups.map(g=><section key={g.name}><h3>{g.name}</h3><div className="media-library-grid">{g.items.map(([name,text])=><details key={name}><summary>{name}<span aria-hidden="true">+</span></summary><p>{text}</p></details>)}</div></section>)}<div className="media-library-cta"><h3>Let’s discuss your filter media needs.</h3><p>Share your application, required grade, dimensions and operating conditions. Our team can discuss suitable media options and the details needed for your enquiry.</p><Link href="/#contact" className="button">Discuss filter media with PARK →</Link></div></section></main><Footer/></>}
