import NextImage from 'next/image';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight, Check } from 'lucide-react';
import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import StructuredData from '../../../components/StructuredData';
import ProductEnquiry from '../../../components/ProductEnquiry';
import Product3D from '../../../components/Product3D';
import { resourceForProduct } from '../../../lib/buyer-resources';
import { productPresentation } from '../../../lib/product-presentation';
import { productDetails } from '../../../lib/product-details';
import { products, toSlug } from '../../../lib/products';
import { pageMetadata, breadcrumb, webPageSchema } from '../../../lib/seo';
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);return p ? pageMetadata(p.name+' | PARK Filtration',p.description,'/products/'+slug,'/images/'+p.image+'.webp') : {title:'Product not found',robots:{index:false}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const p=products.find(p=>p.slug===slug);if(!p)notFound();
 const presentation=productPresentation[slug];const explanation=productDetails[slug];const buyingGuide=resourceForProduct(slug);
 const related=products.filter(item=>item.slug!==slug && item.categories.some(c=>p.categories.includes(c))).slice(0,3);
 return <><Header/><main id="main-content" className="section detail-page"><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/products">Products</Link><span>/</span><span>{p.name}</span></nav>
 <section className="product-introduction" aria-labelledby="product-title"><div className="product-introduction-copy"><span className="eyebrow">{p.categories[0].toUpperCase()} FILTRATION</span><h1 id="product-title">{p.name}</h1><p className="product-introduction-context">{presentation.context}</p><a href="#product-enquiry" className="button small">Discuss your requirement <ArrowUpRight size={16}/></a></div></section>
 <nav className="product-page-nav" aria-label="Product page sections"><a href="#understand-product">The solution</a><a href="#product-range">Product overview</a>{p.variants&&<a href="#product-variants">Media options</a>}<a href="#technical-options">Technical options</a><a href="#product-applications">Applications</a><a href="#product-enquiry">Contact our team</a></nav>
 <section className="product-explanation" id="understand-product"><div className="explanation-columns"><div><h2>What is this filter?</h2><p>{explanation.definition}</p></div><div><h2>How it works</h2><p>{explanation.operation}</p></div></div><div className="product-benefit-grid">{explanation.benefits.map((b,index)=><article key={b.title}><span>0{index+1}</span><h3>{b.title}</h3><p>{b.text}</p></article>)}</div></section>
 <section className="product-range-section" id="product-range"><div className="product-range-heading"><span className="eyebrow">EXPLORE THE PARK RANGE</span><h2>Filtration made for your system.</h2><p>Take a closer look at the filter, then discuss the format and specification for your application.</p></div><div className="detail-grid"><Product3D slug={p.slug} name={p.name} image={p.image}/><div><div className="eyebrow">PARK FILTRATION SOLUTIONS</div><h2 className="product-overview-title">{p.name}</h2><p className="lead">{p.description}</p><div className="material-tags">{p.categories.map(c=><Link key={c} href={'/industries/'+toSlug(c)}>{c}</Link>)}</div><h2 className="detail-subheading">Material</h2><p>{p.material}</p><h2 className="detail-subheading">Features &amp; options</h2><ul className="feature-list">{p.features.map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul><Link href="#product-enquiry" className="button">Discuss this filter <ArrowUpRight size={18}/></Link></div></div></section>


 {explanation.variants ? <section className="product-variants" id="product-variants"><div className="eyebrow">CHOOSE THE FILTRATION FUNCTION</div><h2>Explore the variants</h2><p>Open a variant to understand what it does and what to confirm for your application.</p><div className="variant-grid">{explanation.variants.map((v,index)=><details key={v.name} open={index===0}><summary>{v.image&&<NextImage sizes="90px" src={'/images/'+v.image+'.webp'} alt={v.name} width={90} height={70}/>}<span>{v.name}</span><span className="variant-toggle" aria-hidden="true">+</span></summary><p>{v.explanation}</p><a href="#product-enquiry">Discuss this variant →</a></details>)}</div></section> : p.variants && <section className="application-box" id="product-variants"><h2>Available variants</h2><div className="application-tags">{p.variants.map(v=><span key={v}>{v}</span>)}</div></section>}
 <section className="specifications" id="technical-options"><div className="eyebrow">PRODUCT SPECIFICATIONS</div><h2>Technical options</h2>{p.specifications ? <dl>{p.specifications.map(s=><div key={s.label}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl> : <p>Request confirmation of the selected filter material, dimensions, grade and operating conditions. Send your equipment model and application details for technical confirmation.</p>}<p className="spec-note">Ranges are listed in the supplied PARK product catalogue and describe available options, rather than a single filter specification. Confirm the selected grade, dimensions, test report and operating conditions before ordering. EN 779 references are retained as catalogue terminology.</p></section>
 <section className="application-box" id="product-applications"><div className="eyebrow">DESIGNED FOR YOUR APPLICATION</div><h2>Where it works</h2><div className="application-tags">{p.applications.map(a=><span key={a}>{a}</span>)}</div><p>Final media grade, dimensions and performance specifications are selected for the application. For liquids, confirm chemical compatibility, temperature, flow rate and the required particle rating. For air systems, confirm airflow, pressure drop and installation fit.</p></section>
 <section className="product-selection"><div><div className="eyebrow">BEFORE YOU SELECT</div><h2>Specify with confidence.</h2><Link href="/resources/filter-selection" className="underlined-link">Read the filter selection guide <ArrowUpRight size={16}/></Link></div><ol>{explanation.selection.map(item=><li key={item}>{item}</li>)}</ol></section>{buyingGuide&&<Link className="product-reading-link" href={"/resources/"+buyingGuide.slug}>{buyingGuide.title}<ArrowUpRight size={16}/></Link>}
 <section className="product-faq"><h2>Before you enquire</h2><details><summary>{explanation.question}</summary><p>{explanation.answer}</p></details><details><summary>Can I request a custom size?</summary><p>{slug==='swimming-pool-filter'?'Send the housing dimensions and pool-system details so the team can confirm available formats.':'The catalogue lists standard or customer-specific formats. Share the filter dimensions and system details to confirm availability.'}</p></details><details><summary>What information should I include in my enquiry?</summary><p>Include the application, existing filter dimensions, required media or grade, operating conditions and estimated quantity. Attach an existing drawing or specification when available.</p></details></section>
 <ProductEnquiry product={p.name} variants={explanation.variants?.map(v=>v.name)||p.variants}/>

 <section className="related-products"><h2>Related filtration products</h2><div className="product-grid">{related.map(r=><Link key={r.slug} href={'/products/'+r.slug} className="product-card"><div className="product-image"><NextImage sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 640px" src={'/images/'+r.image+'.webp'} alt={r.name} width={480} height={360} loading="lazy"/></div><div className="product-info"><h3>{r.name}</h3><p>{r.description}</p></div></Link>)}</div></section>
 </main><StructuredData data={breadcrumb([{name:'Home',path:'/'},{name:'Products',path:'/products'},{name:p.name,path:'/products/'+slug}])}/><StructuredData data={webPageSchema(p.name,p.description,'/products/'+slug)}/><Footer/></>;
}
