import Link from 'next/link';
import Header from '../../../components/Header';
import Footer from '../../../components/Footer';

import { pageMetadata } from '../../../lib/seo';
export const metadata = pageMetadata('How to Specify an Air or Liquid Filter | PARK Filtration', 'Understand filter roles, materials, catalogue grades, dimensions, airflow and liquid compatibility before requesting a filtration quotation.', '/resources/filter-selection');
const comparisons = [
 ['Cabin vs engine filter','A cabin filter treats passenger ventilation air. An engine filter treats engine intake air. Their purpose and assemblies differ.','cabin-air-filter','engine-air-filter'],
 ['Panel vs pocket filter','Panel filters use framed pleated media. Pocket filters use extended-surface pockets in an air-handling assembly. Compare the housing, grade, media area and airflow requirement.','panel-filter','pocket-filter'],
 ['Pocket vs industrial bag filter','The pocket filter in this catalogue is for HVAC and air handling. Industrial bag filters are listed for continuous dust collection. Similar names do not make them interchangeable.','pocket-filter','bag-filter'],
 ['Particle vs carbon cabin filter','Particle media retain airborne particles. The catalogue describes activated carbon as adding an adsorption function for odours and certain gases. Specify whether one or both functions are needed.','cabin-air-filter','car-purifier-filter'],
 ['Filter mat vs ceiling filter','Filter mats are listed for broad pre-filtration and equipment applications. Ceiling filters are described for final-stage filtration in paint, spray and ventilation applications. Match the stage and media grade.','filter-mats','ceiling-filter'],
 ['Industrial bag vs cartridge','These are distinct dust-collector formats. Confirm the collector attachment, dimensions and medium. Request a cartridge-specific specification to match your equipment.','bag-filter','cartridge-filter'],
];
export default function Guide(){return <><Header/><main id="main-content"><section className="section buyer-guide"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Filter selection guide</span></nav><div className="eyebrow">A PRACTICAL BUYER'S GUIDE</div><h1>Specify the filter<br/>your system needs.</h1><p className="lead">Start with the job the filter must do. Then define the fit, medium, performance requirement and operating conditions. A catalogue range is a starting point for a specification, rather than a confirmed replacement part.</p><nav className="guide-jump-links" aria-label="Guide sections"><a href="#buying-steps">Selection steps</a><a href="#filter-differences">Product differences</a><a href="#understand-grades">Catalogue grades</a><a href="#enquiry-checklist">Enquiry checklist</a></nav>
 <section id="buying-steps"><h2>From application to specification</h2><div className="guide-step-grid">{[
 ['01','Identify the system','Is the task passenger cabin ventilation, engine intake, battery cooling, railway ventilation, building air handling, paint-booth air, industrial dust collection or liquid filtration? Identify the filter stage and existing equipment.'],
 ['02','Define the contaminants','Describe what needs to be retained or adsorbed. Dust, fine particles, odours and suspended solids call for different catalogue functions. Particle capture alone should not be described as gas removal.'],
 ['03','Measure the assembly','Record the overall dimensions, depth, frame or sealing ring, attachment and existing filter reference. Include a drawing where possible. Appearance alone does not establish fit.'],
 ['04','Confirm operating conditions','Share the flow requirement, temperature, pressure-drop limits and environmental or fluid conditions. Ask the team to confirm the selected medium, grade and technical evidence before ordering.'],
 ].map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section id="filter-differences"><h2>Understand the product differences</h2><div className="guide-comparisons">{comparisons.map(([title,text,a,b])=><article key={title}><h3>{title}</h3><p>{text}</p><div><Link href={'/products/'+a}>Explore first product →</Link><Link href={'/products/'+b}>Explore second product →</Link></div></article>)}</div></section>
 <section id="understand-grades" className="guide-grade-section"><h2>Read catalogue grades in context</h2><p>Filter specifications use ISO 16890, EN 779, EN 1822 and ISO 29463 air-filtration references, as well as micron values for liquid filters. They should be read with the specific product, test method and operating requirement.</p><dl><div><dt>Air-handling ranges</dt><dd>Panel, pocket and battery entries list ISO Coarse and ePM options. Mats and ceiling filters have their own listed ranges. Ask for the exact selected grade and performance at your required airflow.</dd></div><div><dt>Legacy EN 779 terminology</dt><dd>G2–G4, M5–M6 and F7–F9 are legacy classification references; no automatic equivalence to ISO 16890 grades is claimed here.</dd></div><div><dt>Fine-filtration ranges</dt><dd>Our range includes E10, E11, E12, H13, H14 and U15 alongside ISO 29463 ranges. These are distinct options. Request the grade and filter-specific report rather than assuming one efficiency across the range.</dd></div><div><dt>Liquid micron values</dt><dd>The liquid bag entry lists 1.5, 2.5, 7.5, 10 and 34 µm. Confirm the selected rating, how it is tested, fluid compatibility, flow requirement and housing fit.</dd></div></dl><p className="specification-note">Confirm system-specific performance and filter compatibility before ordering. Our team can help specify the selected assembly.</p></section>
 <section id="enquiry-checklist" className="enquiry-checklist"><h2>What to send for a useful quotation</h2><ul><li>Product family and application</li><li>Equipment model or existing filter part number</li><li>Overall dimensions, drawing and attachment or seal requirements</li><li>Required medium, variant and grade, if known</li><li>Airflow or liquid flow and pressure conditions</li><li>Temperature, dust load, liquid identity and chemical exposure where relevant</li><li>Estimated quantity and supply format</li></ul><Link href="/products" className="button">Compare products and request a quote →</Link></section>
 </section></main><Footer/></>}
