import NextImage from 'next/image';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import Header from '../../../components/Header';import Footer from '../../../components/Footer';import StructuredData from '../../../components/StructuredData';
import { industries, products, applicationGroups, applicationProducts, toSlug } from '../../../lib/products';
import { applicationDescriptions } from '../../../lib/industry-content';
import { pageMetadata, breadcrumb } from '../../../lib/seo';
export function generateStaticParams(){return industries.map(i=>({slug:toSlug(i.name)}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const i=industries.find(i=>toSlug(i.name)===slug);return i ? pageMetadata(i.name+' Filtration Solutions | PARK Nonwoven',i.description,'/industries/'+slug,'/images/'+i.image+'.webp') : {title:'Industry not found',robots:{index:false}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const i=industries.find(i=>toSlug(i.name)===slug);if(!i)notFound();return <><Header/><main id="main-content"><section className="industry-page-hero section"><div><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>{i.name}</span></nav><div className="eyebrow">PARK INDUSTRY SOLUTIONS</div><h1>{i.name} filtration solutions</h1><p className="lead">{i.description}</p><Link href="/#contact" className="button">Talk to our team <ArrowUpRight size={18}/></Link></div><NextImage sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 640px" src={`/images/${i.image}.webp`} alt={i.name+' filtration applications'} width={720} height={540} loading="eager" fetchPriority="high"/></section>
 <section className="section industry-applications"><div className="eyebrow">FIND YOUR APPLICATION</div><h2>Filtration for your environment</h2><nav className="application-tags" aria-label="Applications">{applicationGroups[i.name].map(g=><a key={g.name} href={'#'+toSlug(g.name)}>{g.name}</a>)}</nav><div className="application-grid">{applicationGroups[i.name].map(g=><article className="application-card" id={toSlug(g.name)} key={g.name}><h3>{g.name}</h3>{g.children && <p>{g.children.join(' / ')}</p>}<p>{applicationDescriptions[g.name]}</p><ul>{applicationProducts(i.name,g).map(p=><li key={p.slug}><Link href={'/products/'+p.slug}>{p.name}<ArrowUpRight size={15}/></Link></li>)}</ul></article>)}</div><p className="spec-note">Need help narrowing down the options? Share your application, filter dimensions and operating conditions with PARK so we can discuss the right filtration stage and product fit.</p></section>
 <section className="section"><div className="eyebrow">EXPLORE THE RANGE</div><h2>Products for {i.name.toLowerCase()}</h2><div className="product-grid">{products.filter(p=>p.categories.includes(i.name)).map(p=><Link key={p.slug} href={`/products/${p.slug}`} className="product-card"><div className="product-image"><NextImage sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 640px" src={`/images/${p.image}.webp`} alt={p.name} width={480} height={360} loading="lazy"/><div className="circle-arrow"><ArrowUpRight size={20}/></div></div><div className="product-info"><h3>{p.name}</h3><p>{p.description}</p></div></Link>)}</div></section><section className="section industry-next-step"><h2>Let’s work through your filtration needs.</h2><p>Replacing a filter or planning a new system? Start with your application, dimensions and flow requirements. Compare the options here, or send your requirements to our team.</p><div className="products-intro-links"><Link href="/resources/filter-selection">Read the buyer selection guide</Link><Link href="/products">Explore filtration products</Link><Link href="/#contact">Discuss your application with PARK</Link></div></section></main><StructuredData data={breadcrumb([{name:'Home',path:'/'},{name:i.name,path:'/industries/'+slug}])}/><Footer/></>}
